// node --test (type stripping, Node >= 22.18): the pure helpers behind the
// chart addon wizard. Excluded from the app's tsc program.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  fields,
  fromInput,
  getPath,
  inputValue,
  parseSchema,
  parseValuesText,
  placeholder,
  schemaNodes,
  secretPaths,
  setPath,
} from './valuesForm.ts';
import type { FieldNode, GroupNode } from './valuesForm.ts';
import { defaultChartName, installBlockers, isPlanOnly, phaseLabel, portLabel, upgradePlanned, withAddonDefaults } from './addons.ts';
import type { AddonChart } from './api.ts';

const schema = JSON.stringify({
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  required: ['config'],
  properties: {
    replicas: { type: 'integer', title: 'replicas', default: 1, minimum: 1 },
    logLevel: { type: 'string', enum: ['info', 'debug'], default: 'info', description: 'how much the worker says' },
    ratio: { type: ['number', 'null'] },
    metrics: { type: 'object', properties: { enabled: { type: 'boolean', default: true } } },
    config: {
      type: 'object',
      title: 'configuration',
      required: ['password', 'key'],
      properties: {
        password: { type: 'string', writeOnly: true, title: 'database password' },
        key: { type: 'string', writeOnly: true, 'x-zaentrum-generate': 'random-base64-32' },
        url: { type: 'string', format: 'uri' },
      },
    },
    tolerations: { type: 'array', items: { type: 'object' } },
    extra: { type: 'object' },
    'dotted.key': { type: 'string' },
    zaentrum: { type: 'object', properties: { hostname: { type: 'string' } } },
  },
});

test('schemaNodes maps a values schema to form controls', () => {
  const { schema: parsed, error } = parseSchema(schema);
  assert.equal(error, null);
  const nodes = schemaNodes(parsed);
  assert.deepEqual(
    nodes.map((n) => n.path),
    ['replicas', 'logLevel', 'ratio', 'metrics', 'config', 'tolerations', 'extra'],
    'declaration order; a dotted property name and the platform key are left out',
  );
  const byPath = new Map(fields(nodes).map((f) => [f.path, f]));
  const control = (p: string) => byPath.get(p)?.control;
  assert.equal(control('replicas'), 'integer');
  assert.equal(control('logLevel'), 'select');
  assert.equal(control('ratio'), 'number', 'a nullable type is its non-null member');
  assert.equal(control('metrics.enabled'), 'boolean');
  assert.equal(control('config.password'), 'secret', 'writeOnly is a secret input');
  assert.equal(control('config.url'), 'text');
  assert.equal(control('tolerations'), 'json');
  assert.equal(control('extra'), 'json', 'an object without properties has nothing to group');

  const config = nodes.find((n) => n.path === 'config') as GroupNode;
  assert.equal(config.kind, 'group');
  assert.equal(config.title, 'configuration');
  assert.equal(config.required, true);
  const password = byPath.get('config.password') as FieldNode;
  assert.equal(password.title, 'database password');
  assert.equal(password.required, true);
  const key = byPath.get('config.key') as FieldNode;
  assert.equal(key.generate, 'random-base64-32');
  assert.equal(placeholder(key), 'generated by the operator unless set');
  assert.equal(placeholder(byPath.get('replicas') as FieldNode), 'default: 1');
  assert.deepEqual(byPath.get('logLevel')?.options, [
    { label: 'info', value: '"info"' },
    { label: 'debug', value: '"debug"' },
  ]);
  assert.deepEqual(secretPaths(nodes), ['config.password', 'config.key']);
});

test('parseSchema tolerates a chart without a schema and refuses a broken one', () => {
  assert.deepEqual(parseSchema(''), { schema: null, error: null });
  assert.deepEqual(schemaNodes(null), []);
  assert.match(parseSchema('{').error ?? '', /not valid JSON/);
  assert.match(parseSchema('[]').error ?? '', /not a JSON object/);
});

test('setPath and getPath address nested values without mutating them', () => {
  const values = { worker: { replicas: 2 }, keep: true };
  const next = setPath(values, 'config.password', 'x');
  assert.deepEqual(values, { worker: { replicas: 2 }, keep: true });
  assert.equal(getPath(next, 'config.password'), 'x');
  assert.equal(getPath(next, 'config.missing'), undefined);
  assert.equal(getPath(next, 'keep.deeper'), undefined);
  const removed = setPath(setPath(next, 'config.password', undefined), 'worker.replicas', undefined);
  assert.deepEqual(removed, { keep: true }, 'emptied objects go with their last value');
});

test('inputs round-trip through their controls', () => {
  const nodes = schemaNodes(parseSchema(schema).schema);
  const f = new Map(fields(nodes).map((x) => [x.path, x]));
  const field = (p: string) => f.get(p) as FieldNode;

  assert.deepEqual(fromInput(field('replicas'), '3'), { value: 3 });
  assert.deepEqual(fromInput(field('replicas'), '2.5'), { error: 'a whole number' });
  assert.deepEqual(fromInput(field('ratio'), '0.25'), { value: 0.25 });
  assert.deepEqual(fromInput(field('ratio'), 'many'), { error: 'a number' });
  assert.deepEqual(fromInput(field('replicas'), ''), { value: undefined }, 'empty is unset: the default applies');
  assert.deepEqual(fromInput(field('logLevel'), '"debug"'), { value: 'debug' });
  assert.deepEqual(fromInput(field('metrics.enabled'), false), { value: false });
  assert.deepEqual(fromInput(field('tolerations'), '[{"key":"a"}]'), { value: [{ key: 'a' }] });
  assert.deepEqual(fromInput(field('tolerations'), '[{'), { error: 'valid JSON' });

  const values = { replicas: 3, logLevel: 'debug', tolerations: [{ key: 'a' }] };
  assert.equal(inputValue(field('replicas'), values), '3');
  assert.equal(inputValue(field('logLevel'), values), '"debug"');
  assert.equal(inputValue(field('logLevel'), {}), '');
  assert.equal(inputValue(field('metrics.enabled'), {}), true, 'an unset checkbox shows its default');
  assert.equal(inputValue(field('metrics.enabled'), { metrics: { enabled: false } }), false);
  assert.equal(inputValue(field('config.password'), { config: { password: 'never shown' } }), '');
  assert.equal(inputValue(field('tolerations'), values), '[\n  {\n    "key": "a"\n  }\n]');
});

test('pasted values must be a JSON object without the platform key', () => {
  assert.deepEqual(parseValuesText('  '), { values: null, error: null });
  assert.deepEqual(parseValuesText('{"worker":{"replicas":2}}'), { values: { worker: { replicas: 2 } }, error: null });
  assert.match(parseValuesText('{"worker":').error ?? '', /valid JSON/);
  assert.match(parseValuesText('[1]').error ?? '', /JSON object/);
  assert.match(parseValuesText('{"zaentrum":{}}').error ?? '', /platform/);
});

test('defaultChartName mirrors the server', () => {
  assert.equal(defaultChartName('oci://registry.example.org/charts/example'), 'example');
  assert.equal(defaultChartName('oci://registry.example.org:5000/charts/example:1.2.0'), 'example');
  assert.equal(defaultChartName('https://charts.example.org/example-1.2.0.tgz'), 'example');
  assert.equal(defaultChartName('https://charts.example.org/dl/example-worker-v0.3.1-rc.1.tar.gz?token=x'), 'example-worker');
  assert.equal(defaultChartName('https://charts.example.org'), '');
});

test('chart addon states', () => {
  const chart = (over: Partial<AddonChart>): AddonChart => ({
    name: 'example',
    chart: { ref: 'oci://registry.example.org/charts/example', version: '1.2.0' },
    suspended: true,
    phase: 'Planned',
    message: '',
    generation: 2,
    observedGeneration: 2,
    plan: { chart: { name: 'example', version: '1.2.0' }, valuesSchema: '', valuesErrors: [], violations: [], objects: [], workloads: [] },
    components: [],
    lastAppliedChart: null,
    values: null,
    secretKeys: [],
    registered: false,
    ...over,
  });
  assert.deepEqual(installBlockers(chart({})), []);
  assert.equal(installBlockers(chart({ observedGeneration: 1 })).length, 1, 'a plan for an older generation blocks');
  assert.equal(installBlockers(chart({ plan: null })).length, 1);
  const plan = chart({}).plan!;
  assert.deepEqual(installBlockers(chart({ plan: { ...plan, violations: ['Deployment/example: hostPath volume not allowed'], valuesErrors: ['config.password: required'] } })), [
    'Deployment/example: hostPath volume not allowed',
    'config.password: required',
  ]);

  const row = withAddonDefaults({ key: 'example', chart: { ref: 'oci://registry.example.org/charts/example', version: '1.2.0', lastApplied: null }, suspended: true, registered: false });
  assert.equal(isPlanOnly(row), true);
  assert.equal(isPlanOnly(withAddonDefaults({ key: 'legacy' })), false, 'an older portal-api row is an addon added by address');
  const upgrading = withAddonDefaults({
    key: 'example',
    registered: true,
    suspended: true,
    chart: { ref: 'oci://registry.example.org/charts/example', version: '1.3.0', lastApplied: { ref: 'oci://registry.example.org/charts/example', version: '1.2.0' } },
  });
  assert.equal(isPlanOnly(upgrading), false);
  assert.equal(upgradePlanned(upgrading), true);
});

test('phaseLabel words a phase', () => {
  assert.equal(phaseLabel('PlanFailed'), 'plan failed');
  assert.equal(phaseLabel('Ready'), 'ready');
  assert.equal(phaseLabel(''), 'pending');
});

test('portLabel reads every port shape', () => {
  assert.equal(portLabel(8080), '8080');
  assert.equal(portLabel('http'), 'http');
  assert.equal(portLabel({ name: 'http', containerPort: 8080, protocol: 'TCP' }), 'http 8080');
  assert.equal(portLabel({ port: 53, protocol: 'UDP' }), '53/udp');
  assert.equal(portLabel({ odd: true }), '{"odd":true}');
});
